// <auto-generated />
using System;
using System.Collections.Generic;
using AdvoSecureTenant.Core.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdvoSecureTenant.Core.Persistance.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20230320141934_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdvoSecureTenant.Core.Persistance.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("AzureTenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("AdvoSecureTenant.Core.Persistance.Entities.TenantBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TenantBases");
                });

            modelBuilder.Entity("AdvoSecureTenant.Core.Persistance.Entities.TenantBilling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingFirmAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmAddress2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmBankAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmBankBIC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmBankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmVATid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmWeb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingFirmZip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TenantBillings");
                });

            modelBuilder.Entity("AdvoSecureTenant.Core.Persistance.Entities.TenantMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TenantMappings");
                });

            modelBuilder.Entity("AdvoSecureTenant.Core.Persistance.Entities.TenantSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminTenantId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("AvailableTenants")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("TenantSettings");
                });

            modelBuilder.Entity("AdvoSecureTenant.Core.Persistance.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
